version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    #volumes:
    #  - mongodb_data:/data/db

  tic_tac_toe:
    build: .
    container_name: snake-game
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/game_database

#volumes:
#  mongodb_data:
